export const MEMBER_GET = '[MEMBER_GET]Get'
export const MEMBER_SET = '[MEMBER_SET]Get'
export const MEMBER_ADD = '[MEMBER_ADD]add'
export const MEMBER_UPDATE = '[MEMBER_UPDATE]update'
export const MEMBER_DELETE = '[MEMBER_DELETE]delete'
